// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/Elohyrr/k8s-chall-operator",
            "email": "your-email@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/instance": {
            "get": {
                "description": "List all ChallengeInstances, optionally filtered by source_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "List challenge instances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source ID",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source ID (camelCase)",
                        "name": "sourceId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pkg_api.InstanceResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new ChallengeInstance for a user/team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "Create a new challenge instance",
                "parameters": [
                    {
                        "description": "Instance creation request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateInstanceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.InstanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/instance/{challengeId}/{sourceId}": {
            "get": {
                "description": "Get details of a specific ChallengeInstance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "Get a challenge instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge ID",
                        "name": "challengeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source ID (user/team identifier)",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.InstanceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific ChallengeInstance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "Delete a challenge instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge ID",
                        "name": "challengeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source ID (user/team identifier)",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Instance deleted successfully"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg_api.CreateInstanceRequest": {
            "type": "object",
            "properties": {
                "additional": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "challengeId": {
                    "type": "string"
                },
                "challenge_id": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                }
            }
        },
        "pkg_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Instance not found"
                },
                "message": {
                    "type": "string",
                    "example": "challengeinstances.ctf.ctf.io \"chal-101-user\" not found"
                }
            }
        },
        "pkg_api.InstanceResponse": {
            "type": "object",
            "properties": {
                "challenge_id": {
                    "type": "string",
                    "example": "101"
                },
                "connectionInfo": {
                    "type": "string",
                    "example": "http://ctf.instance.user.101.devleo.local"
                },
                "flag": {
                    "description": "Deprecated but kept for compatibility",
                    "type": "string",
                    "example": "FLAG{test}"
                },
                "flags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "FLAG{test}"
                    ]
                },
                "since": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "source_id": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "until": {
                    "type": "string",
                    "example": "2024-01-15T12:30:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "CTF Challenge Operator API Gateway",
	Description:      "API Gateway for managing CTF challenges and instances via Kubernetes CRDs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
